title: AuraOS Documentation & Developer Wiki
description: Ultra-Lightweight Freestanding C Operating System
baseurl: /aura-os
url: https://mirarenanovark.github.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - wiki
  - wiki/**
